export type Tag = { label: string; slug: string; color: string };

export const TAGS: Record<string, Tag> = {
  iceoutmeta: { label: "ICE OUT META", slug: "/iceoutmeta", color: "#e63329" },
  lgbt: { label: "#NoHatefulConduct", slug: "/lgbt", color: "#6d28d9" },
  ai: { label: "AI + Job Security", slug: "/ai", color: "#1d4ed8" },
};

export function formatDate(date: string): string {
  const [year, month, day] = date.split("-");
  return `${month}-${day}-${year}`;
}

export type CardData = {
  outlet: string;
  date: string;
  title: string;
  url: string;
  description: string | null;
  image: string | null;
  tags: string[];
  x: number;
  y: number;
  rot: number;
};

export const ARTICLES: CardData[] = [
  { outlet: "Reuters", date: "2026-04-21", title: "Meta to Start Capturing Employee Mouse Movements and Keystrokes for AI Training Data", description: null, url: "https://www.reuters.com/sustainability/boards-policy-regulation/meta-start-capturing-employee-mouse-movements-keystrokes-ai-training-data-2026-04-21/", image: "/reuters-thumbnail.png", tags: ["ai"], x: 20, y: 55, rot: 1.5 },
  { outlet: "Ken Klippenstein", date: "2026-04-20", title: "Exclusive: ICE Glasses", description: "DHS is developing smart glasses with real-time biometric identification to identify individuals on American streets.", url: "https://www.kenklippenstein.com/p/exclusive-ice-glasses", image: "https://substackcdn.com/image/fetch/$s_!13bS!,f_auto,q_auto:good,fl_progressive:steep/https%3A%2F%2Fsubstack-post-media.s3.amazonaws.com%2Fpublic%2Fimages%2F6567dfc8-786e-4128-b1b4-ddb3e71045e7_2000x1401.png", tags: ["iceoutmeta"], x: 275, y: 15, rot: -1.5 },
  { outlet: "Reuters", date: "2026-04-17", title: "Meta Targets May 20 for First Wave of Layoffs, Additional Cuts Later in 2026", description: null, url: "https://www.reuters.com/world/meta-targets-may-20-first-wave-layoffs-additional-cuts-later-2026-2026-04-17/", image: "/reuters-3.avif", tags: ["ai"], x: 515, y: 65, rot: -1.5 },
  { outlet: "Wired", date: "2026-04-09", title: "How Meta Cafeteria Workers Rallied to Take on ICE", description: "In Seattle, activists inside tech giants are leaning into grassroots fundraising and peer support as petitions and protests draw little response from executives.", url: "https://www.wired.com/story/how-meta-cafeteria-workers-rallied-to-take-on-ice/", image: "https://media.wired.com/photos/69d0484c0c8c2f6a8ef2b8a1/191:100/w_1280,c_limit/How-Meta-Cafeteria-Workers-Rallied-To-Take-On-ICE-Business.jpg", tags: ["iceoutmeta"], x: 778, y: 30, rot: -1 },
  { outlet: "Reuters", date: "2026-03-14", title: "Meta Planning Sweeping Layoffs as AI Costs Mount", description: null, url: "https://www.reuters.com/business/world-at-work/meta-planning-sweeping-layoffs-ai-costs-mount-2026-03-14/", image: "/reuters-4.avif", tags: ["ai"], x: 28, y: 420, rot: 1.5 },
  { outlet: "The Independent", date: "2026-03-12", title: "Immigration Officers Spotted Using Meta AI Smart Glasses During Operations", description: "ICE and Border Patrol are increasingly using government body cameras and facial recognition scanners in deployments across U.S. cities. But some agents are taking matters into their own hands with Meta AI smart glasses.", url: "https://www.independent.co.uk/news/world/americas/us-politics/immigration-officers-meta-ai-glasses-b2937382.html", image: "https://static.independent.co.uk/2026/02/13/7/28/DHS-glasses-split-IndyComp.jpeg?width=1200&height=800&crop=1200:800", tags: ["iceoutmeta"], x: 260, y: 375, rot: -1.5 },
  { outlet: "GoFundMe", date: "2026-02-17", title: "Help Meta Workers Seeking Asylum and Facing Deportation", description: "Meta workers facing deportation need legal fees for filings and lawyers.", url: "https://www.gofundme.com/f/help-meta-workers-seeking-asylum-and-facing-deportation", image: "https://images.gofundme.com/gSR1bNw4RQcxt6802oydvKVZMAA=/1200x900/https://d2g8igdw686xgo.cloudfront.net/100155677_1771353690199620_r.png", tags: ["iceoutmeta"], x: 530, y: 410, rot: 1 },
  { outlet: "The New York Times", date: "2026-02-13", title: "DHS Targets Anti-ICE Posts on Social Media", description: null, url: "https://www.nytimes.com/2026/02/13/technology/dhs-anti-ice-social-media.html", image: "/nyt-thumbnail.webp", tags: ["iceoutmeta"], x: 770, y: 365, rot: 1.5 },
  { outlet: "Bloomberg", date: "2026-01-28", title: "DHS Tried Novel Argument to Compel Meta to Provide User Data", description: null, url: "https://www.bloomberg.com/news/newsletters/2026-01-28/dhs-tried-novel-argument-to-compel-meta-to-provide-user-data", image: "https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iXHXbS9_E2Zo/v6/1200x800.jpg", tags: ["iceoutmeta"], x: 15, y: 765, rot: 2 },
  { outlet: "Wired", date: "2026-01-27", title: "Meta Is Blocking Links to ICE Lists on Facebook, Instagram, and Threads", description: "Users of Meta's social platforms can no longer share links to ICE List, a website listing what it claims are the names of thousands of DHS employees.", url: "https://www.wired.com/story/meta-is-blocking-links-to-ice-list-on-facebook-instagram-and-threads/", image: "https://media.wired.com/photos/6978e52c82bc9b499ef3afed/191:100/w_1280,c_limit/pol-meta-icelist-2233062247.jpg", tags: ["iceoutmeta"], x: 278, y: 725, rot: -2 },
  { outlet: "Axios", date: "2026-01-15", title: "ICE Raids Meta Campus Amid Trump's AI Immigration Push", description: null, url: "https://www.axios.com/2026/01/15/ice-meta-ai-immigration-raid-trump", image: "/axios-thumbnail.webp", tags: ["iceoutmeta"], x: 518, y: 755, rot: 2.5 },
  { outlet: "Bloomberg", date: "2026-01-15", title: "Immigration Officers Descend on Meta Data Center, Arrest Drivers", description: null, url: "https://www.bloomberg.com/news/articles/2026-01-15/immigration-officers-descend-on-meta-data-center-arrest-drivers", image: "https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iED36fabMFdE/v0/1200x800.jpg", tags: ["iceoutmeta"], x: 775, y: 730, rot: -2 },
  { outlet: "404 Media", date: "2025-12-09", title: "Border Patrol Agent Recorded Raid with Meta's Ray-Ban Smart Glasses", description: "A Border Patrol agent wore Meta's Ray-Ban smart glasses during an immigration raid in Charlotte, NC, violating CBP's ban on personal recording devices.", url: "https://www.404media.co/border-patrol-agent-recorded-raid-with-metas-ray-ban-smart-glasses/", image: "https://storage.ghost.io/c/0f/76/0f76b548-bc58-4f25-abc3-3f5ebca07da4/content/images/size/w1200/2025/12/border-patrol-meta-copy.png", tags: ["iceoutmeta"], x: 30, y: 1110, rot: 1 },
  { outlet: "The Intercept", date: "2025-09-18", title: "The Feds Want to Unmask Instagram Accounts That Identified Immigration Agents", description: "StopICE.net filed a motion to quash a subpoena about an Instagram video that identified a Border Patrol agent.", url: "https://theintercept.com/2025/09/18/dhs-subpoena-ice-instagram-dox/", image: "https://theintercept.com/wp-content/uploads/2025/09/crop-Screenshot-2025-09-18-at-2.57.48-PM.jpg?fit=2412%2C1206&w=1200&h=800", tags: ["iceoutmeta"], x: 262, y: 1070, rot: -2.5 },
  { outlet: "Reuters", date: "2025-08-14", title: "Meta's AI Chatbot Guidelines", description: "An internal Meta policy document, seen by Reuters, reveals the social-media giant's rules for chatbots, which have permitted provocative behavior on topics including sex, race and celebrities.", url: "https://www.reuters.com/investigates/special-report/meta-ai-chatbot-guidelines/", image: "/reuters-thumbnail-2.jpg", tags: ["ai"], x: 525, y: 1095, rot: 2 },
  { outlet: "404 Media", date: "2025-08-13", title: "Podcast: Why Are DHS Agents Wearing Meta Ray-Bans?", description: "Examining DHS agents' use of Meta Ray-Ban smart glasses and federal agencies' expanding access to surveillance systems.", url: "https://www.404media.co/podcast-why-are-dhs-agents-wearing-meta-ray-bans/", image: "https://storage.ghost.io/c/0f/76/0f76b548-bc58-4f25-abc3-3f5ebca07da4/content/images/size/w1200/2025/08/ray-ban-yt-cover.jpg", tags: ["iceoutmeta"], x: 778, y: 1080, rot: -1 },
  { outlet: "404 Media", date: "2025-06-16", title: "Meta Users Feel Less Safe Since It Weakened 'Hateful Conduct' Policy, Survey Finds", description: "A survey of 7,000 Meta users from protected groups found that over 90% feel less safe since the company weakened its hateful conduct policy.", url: "https://www.404media.co/meta-users-feel-less-safe-since-it-weakened-hateful-conduct-policy-survey-finds/", image: "https://images.unsplash.com/photo-1675352162363-ac40c3bb8265?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMTc3M3wwfDF8c2VhcmNofDUxfHxtZXRhfGVufDB8fHx8MTc0OTgzOTg5OXww&ixlib=rb-4.1.0&q=80&w=2000", tags: ["lgbt"], x: 20, y: 1430, rot: 1.5 },
  { outlet: "TechCrunch", date: "2025-06-12", title: "The Meta AI App Is a Privacy Disaster", description: "Meta does not indicate to users what their privacy settings are as they post, or where they are even posting to.", url: "https://techcrunch.com/2025/06/12/the-meta-ai-app-is-a-privacy-disaster/", image: "/tech-crunch-thumbnail.webp", tags: ["ai"], x: 278, y: 1410, rot: -2 },
  { outlet: "Human Rights Campaign", date: "2025-01-15", title: "Meta's New Policies: How They Endanger LGBTQ+ Communities", description: "Meta's January 2025 policy changes—ending fact-checking, reducing moderation, and permitting anti-LGBTQ+ rhetoric—create significant safety risks for LGBTQ+ communities.", url: "https://www.hrc.org/news/metas-new-policies-how-they-endanger-lgbtq-communities-and-our-tips-for-staying-safe-online", image: "/hrc-thumbnail.jpg", tags: ["lgbt"], x: 525, y: 1425, rot: -1.5 },
  { outlet: "404 Media", date: "2025-01-10", title: "Meta Deletes Trans and Nonbinary Messenger Themes", description: "Meta deleted trans and nonbinary Messenger themes as policy changes allowed users to declare LGBTQ+ people 'mentally ill.'", url: "https://www.404media.co/meta-deletes-trans-and-nonbinary-messenger-themes/", image: "https://storage.ghost.io/c/0f/76/0f76b548-bc58-4f25-abc3-3f5ebca07da4/content/images/size/w1200/2025/01/Screen-Shot-2025-01-10-at-9.06.11-AM.png", tags: ["lgbt"], x: 775, y: 1415, rot: 2 },
  { outlet: "The Guardian", date: "2025-01-10", title: "Meta terminates its DEI programs days before Trump inauguration", description: "Meta, fresh off announcement to end factchecking, follows McDonald's and Walmart in rolling back diversity initiatives.", url: "https://www.theguardian.com/us-news/2025/jan/10/meta-ending-dei-program", image: "https://i.guim.co.uk/img/media/1b0bb366c015ed132831c4183717c2176bfa9393/907_10_6447_3869/master/6447.jpg?width=1200&height=630&quality=85&auto=format&fit=crop&precrop=40:21,offset-x50,offset-y0&overlay-align=bottom%2Cleft&overlay-width=100p&overlay-base64=L2ltZy9zdGF0aWMvb3ZlcmxheXMvdGctZGVmYXVsdC5wbmc&enable=upscale&s=654c632db2939d42f4d2f62fa9386eab", tags: ["lgbt"], x: 20, y: 1790, rot: 1.5 },
  { outlet: "Wired", date: "2025-01-07", title: "Meta Now Lets Users Say Gay and Trans People Have 'Mental Illness'", description: "Meta rolled out a number of changes to its \"Hateful Conduct\" policy Tuesday as part of a sweeping overhaul of its approach toward content moderation.", url: "https://www.wired.com/story/meta-immigration-gender-policies-change/", image: "https://media.wired.com/photos/677d5cf34db7921e9b5b18e4/191:100/w_1280,c_limit/biz_meta_AP24240376730673.jpg", tags: ["lgbt"], x: 278, y: 1770, rot: -2 },
];
